### ISSUE TITLE
Openchain Server docker Deployment

### ISSUE THREAD

**Issue by ashishrOSS** [openchain/openchain#1]
Hi - I was able to install the openchain server using the docker image but when I try to connect to the server using the browser via http://localhost:8080/ it shows a blank page. I need your help to see how to login into this server and issue an asset?

**Comment by Flavien** [comment]
``http://localhost:8080/`` will return error 404 or 400 which is why you see a blank page. You can test the deployment by trying this URL which should return a JSON response: ``http://localhost:8080/record?key=``.

You can then connect to the server by using the wallet at ``http://nossl.wallet.openchain.org/``. Enter the URL when prompted (``http://localhost:8080/``), or go to "Account" > "Add server..." to do it. You will then be connected to your ledger.

**Comment by ashishrOSS** [comment]
Thanks I was able to connect to my ledger but when I tried to issue an asset it threw an error: transaction could not be confirmed. Unknown error has occured.

**Comment by Flavien** [comment]
If you try to open ``http://localhost:8080/record?key=`` in your browser, do you get a JSON file?

**Comment by ashishrOSS** [comment]
Yes but the values are blank.
{"key":"","value":"","version":""}

**Comment by Flavien** [comment]
Can you run ``docker logs openchain-server`` on your server to see if there is an error there?

**Comment by ashishrOSS** [comment]
Yes there was an error:
info    : [General] [2015-11-19 22:24:24Z] Rejected transaction: The transaction was rejected: InvalidNamespace.
info    : [General] [2015-11-19 22:32:24Z] Rejected transaction: The transaction was rejected: InvalidNamespace.
warning : [Microsoft.AspNet.Server.Kestrel] Connection processing ended abnormally
System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult()
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__77.MoveNext()
warning : [Microsoft.AspNet.Server.Kestrel] Connection shutdown abnormally
System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult()
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__77.MoveNext()
warning : [Microsoft.AspNet.Server.Kestrel] Connection processing ended abnormally
System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult()
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__77.MoveNext()
warning : [Microsoft.AspNet.Server.Kestrel] Connection shutdown abnormally
System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult()
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__77.MoveNext()

**Comment by Flavien** [comment]
I don't know why the connection is reset before you are getting a response (which causes the error to be reported as unknown), but it seems the problem comes from a misconfiguration of the root URL.
Have a look at [this article](https://docs.openchain.org/en/latest/general/troubleshooting.html#error-the-namespace-used-in-the-transaction-is-invalid) to fix it.

**Comment by ashishrOSS** [comment]
I tried setting the root url to http://localhost:8080 and http://<IP>:8080 both failed. Any other ideas?

**Comment by Flavien** [comment]
As mentioned in the article above, you need a trailing slash, so it should be ``http://localhost:8080/``.

**Comment by ashishrOSS** [comment]
Works now - Sorry about that I should have seen that. Thanks for helping in getting this resolved.
