### ISSUE TITLE
Mutation Namespace validation doesn't work

### ISSUE THREAD

**Issue by nivano** [openchain/openchain#13]
as i see in [TransactionValidator.cs lines 92-93](https://github.com/openchain/openchain/blob/master/src/Openchain.Infrastructure/TransactionValidator.cs#L92):
```
if (!mutation.Namespace.Equals(this.Namespace))
                throw new TransactionInvalidException("InvalidNamespace");
```

and  [ByteString.Equals(...)](https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/ByteString.cs#L316)  : 
```
public bool Equals(ByteString other)
        {
            return this == other;
        }
```

ByteString.equals(ByteString) compares references to the objects but not it values. 
so, the code checking namespace from configs to request is invalid?

**Comment by Flavien** [comment]
``mutation.Namespace`` is ``Openchain.ByteString``, not ``Google.Protobuf.ByteString``. Also ``Google.Protobuf.ByteString`` has an overriden == operator.

**Comment by nivano** [comment]
thanks for the comment. i'm not acquainted with c# and have got a problem with calling of Submit Transaction method with InvalidNamespace error code everytime. trying to find what's wrong there.
