### ISSUE TITLE
Update to 1.1

### ISSUE THREAD

**Issue by jayrulez** [openchain/openchain#14]
Any chance this will be updated to .NET Core 1.1?

Also, haven't seen any commits in a while?

Is the project "alive"?

 Would you recommend building a mobile money solution on this at this point?

**Comment by Flavien** [comment]
We've just released 0.7.0 updated to .NET Core 1.1.

Openchain is well suited for a mobile money solution.

**Comment by jayrulez** [comment]
Thank you. We will be evaluating it. Does CoinPrism actively support openchain?

**Comment by Flavien** [comment]
Yes, we support Openchain.
