### ISSUE TITLE
Remove units of an asset from a closed-loop ledger

### ISSUE THREAD

**Issue by jayrulez** [openchain/openchain#16]
We are trying to model a mobile money system on top of openchain.

To satisfy regulators there are certain requirements we must meet.

One in particular is to ensure that the sum of currency on the platform is backed by a bank account.

In a case where a user joins the platform we will issue n units of x currency to the user's account. 

 In a case where the user leaves the platform or wishes to convert a portion of their balance on the platform to fiat currency then how can we remove or retire those portions of the asset from the ledger so the amount of asset on the platform is consistent with the balance of the backing bank account?

@Flavien

**Comment by jayrulez** [comment]
I suspect sending the assets from the user account to the asset account will achieve this?

**Comment by Flavien** [comment]
Removing units of an asset is the opposite process of issuing the asset. In the case of issuance, you create a transaction like:

- Treasury: -10 units
- User A: +10 units

At the end of this, the treasury has a balance of -10, which indicates the total amount of units outstanding.

In the case of redemption:

- Treasury: +10 units
- User A: -10 units

This balances back the treasury towards zero. If you do this with every single one of your users, the treasury will be back to 0 units outstanding.

**Comment by jayrulez** [comment]
That clears it up. Thank you.
