### ISSUE TITLE
Openchain protocol

### ISSUE THREAD

**Issue by rsklyar** [openchain/openchain#2]
are you planning to share any OpenChain protocol specification ?

**Comment by Flavien** [comment]
The Openchain API surface documentation is available [here](https://docs.openchain.org/en/latest/api/method-calls.html).

**Comment by rsklyar** [comment]
ok, how about any description of OpenChain server side architecture ?

**Comment by Flavien** [comment]
The [documentation](https://docs.openchain.org/) should have all the technical details about Openchain. If you want to know how the code actually works, the best is to have a look at the code itself.
