### ISSUE TITLE
Openchain support SharpDevelop IDE

### ISSUE THREAD

**Issue by tiemsn** [openchain/openchain#8]
When open the openchain project with SharpDevelop IDE, it failed with errors bellow.
![image](https://cloud.githubusercontent.com/assets/15994055/16899035/6d43f9c2-4c27-11e6-8350-457880c02a88.png)

I see in the openchain.sln that it support Visual studio 2012, but when I tried with VS2012, it also failed.
Can this project only be opened with Visual studio 2015? VS2015 is too big, It will be much more convenient if openchain support SharpDevelop.

**Comment by Flavien** [comment]
[SharpDevelop doesn't support .NET Core](http://community.sharpdevelop.net/forums/p/22462/57127.aspx). You can use VS Code as an alternative to Visual Studio 2015.
